/**
 * Standalone migration runner (invoked via `bun run db:migrate`).
 *
 * Uses the drizzle-orm migrator against ./drizzle (generated by drizzle-kit)
 * and honors DATABASE_URL from the environment. Fail fast on invalid config;
 * never print secret values.
 */
import path from "node:path";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import { EnvValidationError, loadEnv } from "../config/env";
import { createDb } from "./client";

async function main(): Promise<void> {
	let databaseUrl: string;
	try {
		databaseUrl = loadEnv().DATABASE_URL;
	} catch (error) {
		if (error instanceof EnvValidationError) {
			console.error(error.message);
			process.exitCode = 1;
			return;
		}
		throw error;
	}

	const migrationsFolder = path.resolve(import.meta.dir, "../../drizzle");
	const { sql, db } = createDb(databaseUrl);

	try {
		await migrate(db, { migrationsFolder });
		console.log("Migrations applied successfully.");
	} finally {
		await sql.end({ timeout: 5 });
	}
}

main().catch((error) => {
	console.error(
		`Migration failed: ${error instanceof Error ? error.message : String(error)}`,
	);
	process.exitCode = 1;
});
